version: '3.8'
services:
  backend-service:
    image: flight-ticket:lab1
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    working_dir: /app/backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1