# Generated by Django 4.2.7 on 2025-09-30 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airline', models.CharField(max_length=100)),
                ('aircraft_type', models.CharField(max_length=100)),
                ('economy_seats', models.PositiveIntegerField(default=0)),
                ('business_seats', models.PositiveIntegerField(default=0)),
                ('first_seats', models.PositiveIntegerField(default=0)),
                ('economy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_class', models.CharField(choices=[('economy', '经济舱'), ('business', '商务舱'), ('first', '头等舱')], max_length=20)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_id', models.CharField(max_length=18)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('confirmed', '已确认'), ('cancelled', '已取消'), ('pending', '待确认')], default='confirmed', max_length=20)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
